### ISSUE TITLE
[Bug]: Last ver not working

### ISSUE THREAD

**Issue by d4shsk** [EncryptSL/LiteEco#45]
### What happened?

![image](https://user-images.githubusercontent.com/75478355/226669032-9e095311-715c-4a5c-8907-5fb40b828331.png)
I'm getting this error

### Plugin Version

1.3.0-SNAPSHOT

### You detected problem on this server platform ?

PaperMC

**Comment by d4shsk** [comment]
ver 1.2.5 is working properly

**Comment by EncryptSL** [comment]
This not seems like a bug from LiteEco, but you can dump from /version and /plugins.

Problem can be related to new paper plugins system, if some plugin use new platform for paper plugins.

**Comment by exkuretrol** [comment]
I have the same problem with paper-1.19.2 ([git-Paper-307](https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/307/downloads/paper-1.19.2-307.jar))

here is my `/version` output
```
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
```

and `/plugins` output

```
Plugins (6): BentoBox, FreedomChat, LiteEco, LuckPerms, PlaceholderAPI, Vault
```

**Comment by EncryptSL** [comment]
Maybe fixed in 1.3.1-SNAPSHOT, please test this release https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/

**Comment by exkuretrol** [comment]
> 

hi EncryptSL, thanks for your quick hot fix! You did a really good job. But I still get the Error on my paper server (1.19.2, build 307). The Error message list below:

```
[14:15:20 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] class encryptsl.cekuj.net.api.ConfigAPI tried to access field org.bukkit.plugin.java.JavaPlugin.logger (encryptsl.cekuj.net.api.ConfigAPI is in unnamed module of loader 'LiteEco-1.3.1-SNAPSHOT.jar' @48bad53d; org.bukkit.plugin.java.JavaPlugin is in unnamed module of loader java.net.URLClassLoader @421faab1) initializing LiteEco v1.3.1-SNAPSHOT (Is it up to date?)
java.lang.IllegalAccessError: class encryptsl.cekuj.net.api.ConfigAPI tried to access field org.bukkit.plugin.java.JavaPlugin.logger (encryptsl.cekuj.net.api.ConfigAPI is in unnamed module of loader 'LiteEco-1.3.1-SNAPSHOT.jar' @48bad53d; org.bukkit.plugin.java.JavaPlugin is in unnamed module of loader java.net.URLClassLoader @421faab1)
        at encryptsl.cekuj.net.api.ConfigAPI.create(ConfigAPI.kt:19) ~[LiteEco-1.3.1-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.LiteEco.onLoad(LiteEco.kt:44) ~[LiteEco-1.3.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Artucuno** [comment]
Hey, I'm trying to use the latest snapshot but I'm getting an error
```
[02:36:33 ERROR]: [LiteEco] Error initializing plugin 'LiteEco-1.3.2-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalAccessError: class encryptsl.cekuj.net.api.ConfigAPI tried to access private field org.bukkit.plugin.java.JavaPlugin.logger (encryptsl.cekuj.net.api.ConfigAPI is in unnamed module of loader 'LiteEco-1.3.2-SNAPSHOT.jar' @2fa7e089; org.bukkit.plugin.java.JavaPlugin is in unnamed module of loader java.net.URLClassLoader @421faab1)
        at encryptsl.cekuj.net.api.ConfigAPI.createConfig(ConfigAPI.kt:28) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
        at encryptsl.cekuj.net.LiteEco.onLoad(LiteEco.kt:45) ~[LiteEco-1.3.2-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-521]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-521]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.19.4.jar:git-Paper-521]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-521]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-521]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-521]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by EncryptSL** [comment]
Idk, try use last update 1.3.3-SNAPSHOT there seems problem be solved.

Problem is with kotlin and accessing to the logger instead getLogger()
