### ISSUE TITLE
[Question]: 1.19.4

### ISSUE THREAD

**Issue by jilienecircelli** [EncryptSL/LiteEco#49]
### Your Question

Hello, when do you think you will be adding 1.19.4 support? Some of the commands do not run on the current version with a 1.19.4 server.

Thank you!

**Comment by EncryptSL** [comment]
Hello, commands not working on this version ? Can yo please send something from log/error or exception. 
Because i don't have any information.

Thanks.

**Comment by LWJerri** [comment]
Spigot 1.19.4:

```
[22:54:31] [Server thread/INFO]: [LiteEco] Loading 5 libraries... please wait
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.8.0/kotlin-stdlib-jdk8-1.8.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlin/kotlin-stdlib/1.8.0/kotlin-stdlib-1.8.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlin/kotlin-stdlib-common/1.8.0/kotlin-stdlib-common-1.8.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/annotations/13.0/annotations-13.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.8.0/kotlin-stdlib-jdk7-1.8.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/exposed/exposed-core/0.40.1/exposed-core-0.40.1.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlin/kotlin-reflect/1.7.20/kotlin-reflect-1.7.20.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.6.4/kotlinx-coroutines-core-jvm-1.6.4.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/org/jetbrains/exposed/exposed-jdbc/0.40.1/exposed-jdbc-0.40.1.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/com/squareup/okhttp3/okhttp/4.10.0/okhttp-4.10.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loaded library /data/libraries/com/squareup/okio/okio-jvm/3.0.0/okio-jvm-3.0.0.jar
[22:54:31] [Server thread/INFO]: [LiteEco] Loading LiteEco v1.3.2-SNAPSHOT
[22:54:31] [Server thread/INFO]: [LiteEco] Configuration database.db exist !
[22:54:31] [Server thread/INFO]: [LiteEco] Configuration config.yml is latest !
[22:54:31] [Server thread/INFO]: HikariPool-1 - Starting...
[22:54:31] [Server thread/INFO]: HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@2b14a070
[22:54:31] [Server thread/INFO]: HikariPool-1 - Start completed.
[22:54:31] [Server thread/INFO]: SQL: CREATE TABLE IF NOT EXISTS lite_eco (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid VARCHAR(36) NOT NULL, money DOUBLE PRECISION NOT NULL)
[22:54:32] [Server thread/INFO]: [LiteEco] Enabling LiteEco v1.3.2-SNAPSHOT
[22:54:32] [Server thread/INFO]: [LiteEco] PlaceholderAPI hook not found
[22:54:32] [Server thread/INFO]: [LiteEco] Registered Vault like a service.
[22:54:32] [Server thread/INFO]: [LiteEco] Treasury not found, for better experience please download Treasury or Vault.
[22:54:33] [Server thread/INFO]: [LiteEco] You are using current version !
[22:54:33] [Server thread/INFO]: [LiteEco] Registering commands with Cloud Command Framework !
[22:54:33] [Server thread/ERROR]: Error occurred while enabling LiteEco v1.3.2-SNAPSHOT (Is it up to date?)
encryptsl.cekuj.net.cloud.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: version too high ()
        at encryptsl.cekuj.net.cloud.bukkit.BukkitCommandManager.registerBrigadier(BukkitCommandManager.java:343) ~[?:?]
        at encryptsl.cekuj.net.cloud.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:125) ~[?:?]
        at encryptsl.cekuj.net.LiteEco.registerCommands(LiteEco.kt:86) ~[?:?]
        at encryptsl.cekuj.net.LiteEco.onEnable(LiteEco.kt:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:534) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3744-Spigot-d1bd3bd-a7cfc77]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:448) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3744-Spigot-d1bd3bd-a7cfc77]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3744-Spigot-d1bd3bd-a7cfc77]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3744-Spigot-d1bd3bd-a7cfc77]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3744-Spigot-d1bd3bd-a7cfc77]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by EncryptSL** [comment]
Guys & Girls you can try use new update 1.3.3 https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/update?update=499005

Probably fixed by updated libraries.

**Comment by jilienecircelli** [comment]
Thank you! I will update and let you know.

**Comment by jilienecircelli** [comment]
No, sadly the error is still occurring when I try to run /bal or /baltop or /money commands.


`- [Sat 10:30:53 ERROR LiteEco] Exception executing command handler
java.lang.NullPointerException: ofNullable(langConfigura….replace("<key>", value)) must not be null
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.config.TranslationConfig.getMessage(TranslationConfig.kt:17)
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.commands.MoneyCMD.onTopBalance(MoneyCMD.kt:106)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.cloud.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79)
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101)
    at LiteEco-1.3.3-SNAPSHOT.jar//encryptsl.cekuj.net.cloud.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131)
    at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
  [Sat 10:30:59 INFO  Server/LoginListener] UUID of player GoodGuyRichard is 24936968-fe52-48ed-a929-2366601d26f1`

**Comment by EncryptSL** [comment]
Please check if your config file is validate with files on github page. This seems like bad config or language file because all working.

In every update if is configuration changed, you must delete old configuration...

You can confirm this.

1. Step stop server.
2. Upload new update
3. Delete all langs and config from LiteEco file.
4. Start server send log.
