### ISSUE TITLE
[Bug]: No Database connection

### ISSUE THREAD

**Issue by DevSnx** [EncryptSL/LiteEco#93]
### What happened?

I dont can connect to my MariaDB database?

### Plugin Version

Version 1.5.0-SNAPSHOT

### You detected problem on this server platform ?

PaperMC

### Version /version - output

```shell
[feuerbrunnen-1][11:59:25 INFO]: Checking version, please wait...
[feuerbrunnen-1][11:59:25 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[feuerbrunnen-1]You are 1 version(s) behind
[feuerbrunnen-1]Download the new version at: https://papermc.io/downloads/paper
```

### Relevant log output

```shell
[11:34:52] [Server thread/WARN]: [Exposed] Transaction attempt #0 failed: Unknown column 'RESERVED' in 'where clause'. Statement(s): null
java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1286) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1180) ~[mysql-connector-j-8.4.0.jar:8.4.0]
	at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSQLKeywords(HikariProxyDatabaseMetaData.java) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$identifierManager$2.invoke(JdbcDatabaseMetadataImpl.kt:58) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$identifierManager$2.invoke(JdbcDatabaseMetadataImpl.kt:56) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$lazyMetadata$1.invoke(JdbcDatabaseMetadataImpl.kt:396) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:56) ~[?:?]
	at org.jetbrains.exposed.sql.Database$identifierManager$2$1.invoke(Database.kt:76) ~[?:?]
	at org.jetbrains.exposed.sql.Database$identifierManager$2$1.invoke(Database.kt:76) ~[?:?]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:72) ~[?:?]
	at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:44) ~[?:?]
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:76) ~[?:?]
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:76) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:76) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:329) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:325) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.fullIdentity$exposed_core(Transaction.kt:325) ~[?:?]
	at org.jetbrains.exposed.sql.Column.toQueryBuilder(Column.kt:52) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:58) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.unaryPlus(Expression.kt:67) ~[?:?]
	at org.jetbrains.exposed.sql.Query$prepareSQL$2$2.invoke(Query.kt:177) ~[?:?]
	at org.jetbrains.exposed.sql.Query$prepareSQL$2$2.invoke(Query.kt:177) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.appendTo(Expression.kt:31) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.appendTo$default(Expression.kt:22) ~[?:?]
	at org.jetbrains.exposed.sql.Query$prepareSQL$2.invoke(Query.kt:177) ~[?:?]
	at org.jetbrains.exposed.sql.Query$prepareSQL$2.invoke(Query.kt:164) ~[?:?]
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19) ~[?:?]
	at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:164) ~[?:?]
	at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:52) ~[?:?]
	at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:9) ~[?:?]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:292) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:269) ~[?:?]
	at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:83) ~[?:?]
	at kotlin.collections.CollectionsKt___CollectionsKt.singleOrNull(_Collections.kt:647) ~[?:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.models.DatabaseEcoModel.getUserByUUID$lambda$6(DatabaseEcoModel.kt:54) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$lambda$0(DatabaseLoggerTransaction.kt:14) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:324) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:371) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:370) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:279) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249) ~[?:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction(DatabaseLoggerTransaction.kt:11) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$default(DatabaseLoggerTransaction.kt:10) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.models.DatabaseEcoModel.getUserByUUID(DatabaseEcoModel.kt:51) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.api.economy.DeprecatedLiteEcoEconomyImpl.getUserByUUID(DeprecatedLiteEcoEconomyImpl.kt:52) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.api.economy.DeprecatedLiteEcoEconomyImpl.getBalance(DeprecatedLiteEcoEconomyImpl.kt:59) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at LiteEco-1.5.0-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.hook.placeholderapi.EconomyPlaceholderAPI.onRequest(EconomyPlaceholderAPI.kt:31) ~[LiteEco-1.5.0-SNAPSHOT.jar:?]
	at PlaceholderAPI-2.11.6 (4).jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6 (4).jar:?]
	at PlaceholderAPI-2.11.6 (4).jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6 (4).jar:?]
	at PlaceholderAPI-2.11.6 (4).jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6 (4).jar:?]
	at original-CityQuest-1.0-SNAPSHOT.jar/eu.xaldrion.devsnx.cityquest.manager.PlayerManager$PlayerData.setScoreboard(PlayerManager.java:72) ~[original-CityQuest-1.0-SNAPSHOT.jar:?]
	at original-CityQuest-1.0-SNAPSHOT.jar/eu.xaldrion.devsnx.cityquest.manager.PlayerManager$PlayerData$1.run(PlayerManager.java:62) ~[original-CityQuest-1.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by tim-schneider** [comment]
Reproducible for me with MariaDB 11.X, not a issue under MariaDB 10.6.X

**Comment by EncryptSL** [comment]
Probably fixed in 1.5.1 not tested.

**Comment by tim-schneider** [comment]
Thank you for updating the dependencies! Unfortunately still the same.

```
[21:35:41 INFO]: [LiteEco] Loading server plugin LiteEco v1.5.2-SNAPSHOT
[21:35:41 INFO]: [LiteEco] Loaded translation en_us.yml [!]
[21:35:41 INFO]: [com.zaxxer.hikari.HikariDataSource] LiteEco - Starting...
[21:35:41 INFO]: [com.zaxxer.hikari.pool.HikariPool] LiteEco - Added connection com.mysql.cj.jdbc.ConnectionImpl@7554518a
[21:35:41 INFO]: [com.zaxxer.hikari.HikariDataSource] LiteEco - Start completed.
[21:35:41 WARN]: [Exposed] Transaction attempt #0 failed: Unknown column 'RESERVED' in 'WHERE'. Statement(s): null
java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'WHERE'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1312) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1185) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSQLKeywords(HikariProxyDatabaseMetaData.java) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.identifierManager_delegate$lambda$16(JdbcDatabaseMetadataImpl.kt:103) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.lazyMetadata$lambda$77(JdbcDatabaseMetadataImpl.kt:603) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:101) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19$lambda$18(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:72) ~[?:?]
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:44) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19(Database.kt:91) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:318) ~[?:?]
        at org.jetbrains.exposed.sql.Table.createStatement(Table.kt:1712) ~[?:?]
        at org.jetbrains.exposed.sql.DdlAware$DefaultImpls.getDdl(Constraints.kt:25) ~[?:?]
        at org.jetbrains.exposed.sql.Table.getDdl(Table.kt:438) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.tableDdlWithoutExistingSequence(SchemaUtils.kt:115) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:495) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:493) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect$lambda$1(DatabaseConnector.kt:28) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$lambda$0(DatabaseLoggerTransaction.kt:14) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:355) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$lambda$11(ThreadLocalTransactionManager.kt:402) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:401) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$lambda$5(ThreadLocalTransactionManager.kt:310) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:259) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction(DatabaseLoggerTransaction.kt:11) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$default(DatabaseLoggerTransaction.kt:10) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect(DatabaseConnector.kt:27) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.onLoad(LiteEco.kt:70) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:563) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[21:35:41 WARN]: [Exposed] Wait 0 milliseconds before retrying
[21:35:41 WARN]: [Exposed] Transaction attempt #1 failed: Unknown column 'RESERVED' in 'WHERE'. Statement(s): null
java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'WHERE'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1312) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1185) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSQLKeywords(HikariProxyDatabaseMetaData.java) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.identifierManager_delegate$lambda$16(JdbcDatabaseMetadataImpl.kt:103) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.lazyMetadata$lambda$77(JdbcDatabaseMetadataImpl.kt:603) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:101) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19$lambda$18(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:72) ~[?:?]
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:44) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19(Database.kt:91) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:318) ~[?:?]
        at org.jetbrains.exposed.sql.Table.createStatement(Table.kt:1712) ~[?:?]
        at org.jetbrains.exposed.sql.DdlAware$DefaultImpls.getDdl(Constraints.kt:25) ~[?:?]
        at org.jetbrains.exposed.sql.Table.getDdl(Table.kt:438) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.tableDdlWithoutExistingSequence(SchemaUtils.kt:115) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:495) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:493) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect$lambda$1(DatabaseConnector.kt:28) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$lambda$0(DatabaseLoggerTransaction.kt:14) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:355) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$lambda$11(ThreadLocalTransactionManager.kt:402) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:401) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$lambda$5(ThreadLocalTransactionManager.kt:310) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:259) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction(DatabaseLoggerTransaction.kt:11) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$default(DatabaseLoggerTransaction.kt:10) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect(DatabaseConnector.kt:27) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.onLoad(LiteEco.kt:70) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:563) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[21:35:41 WARN]: [Exposed] Wait 0 milliseconds before retrying
[21:35:41 WARN]: [Exposed] Transaction attempt #2 failed: Unknown column 'RESERVED' in 'WHERE'. Statement(s): null
java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'WHERE'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1312) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1185) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSQLKeywords(HikariProxyDatabaseMetaData.java) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.identifierManager_delegate$lambda$16(JdbcDatabaseMetadataImpl.kt:103) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.lazyMetadata$lambda$77(JdbcDatabaseMetadataImpl.kt:603) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:101) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19$lambda$18(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:72) ~[?:?]
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:44) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19(Database.kt:91) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:318) ~[?:?]
        at org.jetbrains.exposed.sql.Table.createStatement(Table.kt:1712) ~[?:?]
        at org.jetbrains.exposed.sql.DdlAware$DefaultImpls.getDdl(Constraints.kt:25) ~[?:?]
        at org.jetbrains.exposed.sql.Table.getDdl(Table.kt:438) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.tableDdlWithoutExistingSequence(SchemaUtils.kt:115) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:495) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:493) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect$lambda$1(DatabaseConnector.kt:28) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$lambda$0(DatabaseLoggerTransaction.kt:14) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:355) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$lambda$11(ThreadLocalTransactionManager.kt:402) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:401) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$lambda$5(ThreadLocalTransactionManager.kt:310) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:259) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction(DatabaseLoggerTransaction.kt:11) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$default(DatabaseLoggerTransaction.kt:10) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect(DatabaseConnector.kt:27) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.onLoad(LiteEco.kt:70) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:563) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[21:35:41 ERROR]: [LiteEco] Error initializing plugin 'LiteEco-1.5.2-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.sql.SQLSyntaxErrorException: Unknown column 'RESERVED' in 'WHERE'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1312) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getSQLKeywords(DatabaseMetaDataUsingInfoSchema.java:1185) ~[mysql-connector-j-9.1.0.jar:9.1.0]
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getSQLKeywords(HikariProxyDatabaseMetaData.java) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcIdentifierManager.<init>(JdbcIdentifierManager.kt:14) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.identifierManager_delegate$lambda$16(JdbcDatabaseMetadataImpl.kt:103) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.lazyMetadata$lambda$77(JdbcDatabaseMetadataImpl.kt:603) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getIdentifierManager(JdbcDatabaseMetadataImpl.kt:101) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19$lambda$18(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:72) ~[?:?]
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:44) ~[?:?]
        at org.jetbrains.exposed.sql.Database.identifierManager_delegate$lambda$19(Database.kt:91) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt:91) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:318) ~[?:?]
        at org.jetbrains.exposed.sql.Table.createStatement(Table.kt:1712) ~[?:?]
        at org.jetbrains.exposed.sql.DdlAware$DefaultImpls.getDdl(Constraints.kt:25) ~[?:?]
        at org.jetbrains.exposed.sql.Table.getDdl(Table.kt:438) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.tableDdlWithoutExistingSequence(SchemaUtils.kt:115) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:495) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:493) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect$lambda$1(DatabaseConnector.kt:28) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$lambda$0(DatabaseLoggerTransaction.kt:14) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:355) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$lambda$11(ThreadLocalTransactionManager.kt:402) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:401) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$lambda$5(ThreadLocalTransactionManager.kt:310) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:410) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:259) ~[?:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction(DatabaseLoggerTransaction.kt:11) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.extensions.DatabaseLoggerTransactionKt.loggedTransaction$default(DatabaseLoggerTransaction.kt:10) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.common.database.DatabaseConnector.initConnect(DatabaseConnector.kt:27) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at LiteEco-1.5.2-SNAPSHOT.jar/com.github.encryptsl.lite.eco.LiteEco.onLoad(LiteEco.kt:70) ~[LiteEco-1.5.2-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:563) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-221-c467df9]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[21:35:41 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:35:41 INFO]: [Vault] Enabling Vault v2.9.0
[21:35:41 INFO]: [Vault] Enabled Version 2.9.0
[21:35:41 INFO]: [LiteEco] Enabling LiteEco v1.5.2-SNAPSHOT
[21:35:41 INFO]: [LiteEco] Blocked plugins are now 2
[21:35:41 WARN]: [LiteEco] Warning plugin PlaceholderAPI not found !
[21:35:41 WARN]: [LiteEco] Keep in mind without PlaceholderAPI, you can't use LiteEco placeholders.
[21:35:41 WARN]: [LiteEco] Warning plugin MiniPlaceholders not found !
[21:35:41 WARN]: [LiteEco] Keep in mind without MiniPlaceholders, you can't use LiteEco placeholders.
[21:35:41 INFO]: [LiteEco] VaultUnlocked is registered, LiteEco now using v2 modern economy provider !
[21:35:41 WARN]: [LiteEco] Warning plugin Treasury not found !
[21:35:41 WARN]: [LiteEco] For better experience please download Treasury or Vault.
[21:35:41 WARN]: [LiteEco] Keep in mind without Treasury, LiteEco can't use API from Treasury.
[21:35:41 INFO]: [LiteEco] You are using current version !
[21:35:41 INFO]: [LiteEco] Registering commands with Cloud Command Framework !
[21:35:42 INFO]: [LiteEco] Bukkit Listener AccountManageListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener PlayerEconomyPayListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyGlobalDepositListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyGlobalSetListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyGlobalWithdrawListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyMoneyDepositListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyMoneyWithdrawListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener EconomyMoneySetListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener PlayerLoginListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener PlayerJoinListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Bukkit Listener PlayerQuitListener registered () -> ok
[21:35:42 INFO]: [LiteEco] Listeners registered (11) in time 6 ms -> ok
[21:35:42 INFO]: [LiteEco] Config was updated on current version !
[21:35:42 INFO]: [LiteEco] Plugin enabled in time 342 ms
```

tested with

```
podman run --detach --name mariadb -p 3306:3306 \
-e MYSQL_ROOT_PASSWORD="XXXX" -e MYSQL_DATABASE=mc \
-e MYSQL_USER=mc -e MYSQL_PASSWORD=YYYY -e TZ=Europe/Berlin \
--volume /srv/mysqldata:/var/lib/mysql docker.io/mariadb:11


podman run -p 25565:25565 -e EULA=TRUE \
--network=pasta:-T,3306:3306 \
-e TYPE=PAPER -e VERSION=1.21.4 -d --name mc  \
-v /srv/mcdata:/data \
docker.io/itzg/minecraft-server:java23
```

**Comment by EncryptSL** [comment]
https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-21-x.101934/update?update=585632

Added permission lite.eco.pay.(currency)
Added permission lite.eco.balance.(currency)
Added permission lite.eco.balance.* and lite.eco.pay.*

Maybe in next release i add permission for check other players balances, this is not now priority in my list.

```YAML
# Allow use selected currency
lite.eco.balance.(currency)
# Allow pay with selected currency
lite.eco.pay.(currency)
# Allow suggests and use of all exists currencies.
lite.eco.balance.*
# Allow pay with all currencies.
lite.eco.pay.*
```

Fix for MariaDB Connection new value in config.
Important is part with driverClassName and small change in jdbc_url from mysql to mariadb.....

```YAML
# Settings for Database or SQLite connection.
database:
  # For SQLite, the path to the SQLite database file: jdbc:sqlite:plugins/LiteEco/database.db
  # For MySQL, the JDBC connection URL in the format: jdbc:mysql://your_host:port/name_of_database
  # For MariaDB, the JDBC connection URL in the format: jdbc:mariadb://your_host:port/name_of_database

  # Drivers:
  #
  # MariaDB - org.mariadb.jdbc.Driver (https://youtrack.jetbrains.com/issue/EXPOSED-170)
  # MySQL - com.mysql.cj.jdbc.Driver Don't use if you have MariaDB version 11.X and newer.
  # SQL - org.sqlite.JDBC
  connection:
    # Settings for DriverClassName
    driverClassName: "org.sqlite.JDBC"
    # Settings for JDBC_HOST
    jdbc_url: "jdbc:sqlite:plugins/LiteEco/database.db"
    # The username of the user to connect to your database (MySQL only).
    username: user_name
    # The password of the user to connect to your database (MySQL only).
    password: password
```

**Comment by EncryptSL** [comment]
I believe this fixed your issue.

**Comment by tim-schneider** [comment]
Many thanks for the fast update! Works fine now. Tested with MariaDB Server version 11.7.2
